config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'pages#index'

  resources :friends
  get '/search', to: 'friends#search'
  get '/requests', to: 'friends#requests'
  get '/truefriends', to: 'friends#truefriends'
  post '/login', to: 'pages#login'
  get '/login', to: 'pages#login_box'
  get '/register', to: 'pages#register'
  post '/register', to: 'pages#new_register'
  get '/logout', to: 'pages#logout'
  put '/profile', to: 'pages#profile'
  post '/friends/:id/addvalue', to: 'values#add'
  get '/friends/:id/values', to: 'values#show'
  patch '/friends/:id/add_back', to: 'friends#add_back'

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: "User"
  validate :self_add_friend

  def self_add_friend
    if friend_id == user_id
      errors.add(:friend_id, 'You cannot add yourself.')
    end
  end

  protected
  before_create do
    other = Friendship.find_by(user_id: self.friend_id, friend_id: self.user_id)
    if other
      other.update(status: true)
      self.status = true
    end
  end

  def self.friends(id)
    friendships = Friendship.where(user_id: id, status: true)
    friendships.map{|friendship| User.find(friendship.friend_id)}
  end

  def self.friend_requests(id)
    friendships = Friendship.where(friend_id: id, status: nil)
    friends = friendships.map{|friendship| User.find(friendship.user_id)}
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, uniqueness: true

  has_many :user_values
  has_many :values, through: :user_values
  has_many :friendships
  has_many :friends, through: :friendships, class_name: 'User'

end

app/models/user_value.rb
class UserValue < ActiveRecord::Base
  belongs_to :user
  belongs_to :value

  def self.values_of_user(user_id)
    user_values = UserValue.where(user_id: user_id).includes(:value)
    values = user_values.map {|user_value| user_value.value}
  end
end

app/models/value.rb
class Value < ActiveRecord::Base
  belongs_to :users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  include IndexHelper
  def truefriends
    friends = Friendship.friends(current_user.id)
    render partial: 'friends/friendslist', locals: {friends: friends, button: "unfriend"}
  end

  def requests
    friends = Friendship.friend_requests(current_user.id)
    render partial: 'friends/friendslist', locals: {friends: friends, button: "add"}
  end

  def search
    friends = User.where(email: params[:email])
    render partial: 'friends/friendslist', locals: {friends: friends, button: "add"}
  end

  def show
    ship = Friendship.find_by(user_id: current_user.id, friend_id: params[:id])
    request_received = Friendship.find_by(user_id: params[:id], friend_id: current_user.id) != nil
    request_sent = Friendship.find_by(friend_id: params[:id], user_id: current_user.id) != nil
    if ship && ship.status
      friend = User.find(params[:id])
      moreValues = Value.all.shuffle[0..50]
      values = UserValue.values_of_user(params[:id])
      render '/values/friendvalues', locals: {friend: friend, values: values, moreValues: moreValues, request_sent: request_sent}
    else
      friend = User.find(params[:id])
      values = UserValue.values_of_user(params[:id])
      render '/values/friendvalues', locals: {friend: friend, values: [], moreValues: [], request_received: request_received, request_sent: request_sent}
    end
  end

  def add_back
    ship = Friendship.create(user_id: current_user.id, friend_id: params[:id])
    moreValues = Value.all.shuffle[0..50]
    values = UserValue.values_of_user(params[:id])
    render partial: '/values/iffriend', locals: {friend: User.find(params[:id]), values: values, moreValues: moreValues}
  end

  def update
    Friendship.create(user_id: current_user.id, friend_id: params[:id])
    friends = Friendship.friend_requests(current_user.id)
    render partial: 'friends/friendslist', locals: {friends: friends, button: "add"}
  end

  def destroy
    my_friendship = Friendship.find_by(user_id: current_user.id, friend_id: params[:id]).destroy
    fri_friendship = Friendship.find_by(user_id: params[:id], friend_id: current_user.id).destroy

    friends = Friendship.friends(current_user.id)

    render partial: 'friends/friendslist', locals: {friends: friends, button: "unfriend"}
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include IndexHelper
  def index
    your_values = current_user ? UserValue.values_of_user(current_user.id) : nil
    render 'show', locals: {your_values: your_values}
  end

  def login
    user = User.find_by(email: params[:user][:email])
    if user && user.authenticate(params[:user][:password])
      session[:user_id] = user.id
      your_values = UserValue.values_of_user(current_user.id)
      redirect_to '/', locals: {your_values: your_values}
    else
      session[:error] = "Invalid Login Information"
      render 'show'
    end
  end

  def profile
    current_user.update(bio: params[:newbio])
    render nothing: true
  end

  def register
    render partial: 'register'
  end

  def login_box
    render partial: 'logedout'
  end

  def logout
    session[:user_id] = nil
    redirect_to '/'
  end

  def new_register
    user = User.create(user_params)
    user.update(bio: "Edit bio...")
    session[:user_id] = user.id
    redirect_to '/'
  end

private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :salt, :encrypted_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include IndexHelper
end

app/controllers/values_controller.rb
 class ValuesController < ApplicationController
  include IndexHelper
  def show
    moreValues = Value.all.shuffle[0..50]
    friend = User.find(params[:id])
    values = UserValue.values_of_user(params[:id])
    render partial: '/values/possiblevalues', locals: {moreValues: moreValues, friend: friend, values: values}
  end

  def add
    if params[:value_id]
      UserValue.find_or_create_by(user_id: params[:id], value_id: params[:value_id])
    else
      newValue = Value.find_or_create_by(word: params[:word].downcase)
      UserValue.create(user_id: params[:id], value_id: newValue.id)
    end
    values = UserValue.values_of_user(params[:id])
    render partial: 'values/addedvalues', locals: {values: values}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/index_helper.rb
module IndexHelper
  def current_user
    session[:user_id] ? User.find(session[:user_id]) : nil
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friends/_friendslist.html.erb
<ul id='friendlist'>
  <% friends.each do |friend| %>
    <% if friend.id != current_user.id %>
      <li>
        <a href='/friends/<%= friend.id %>'><%= friend.first_name %> <%= friend.last_name %></a>

        <%= button_to button, friend_path(friend), method: (button == 'add' ? :put : :delete), class: button %>

      </li>
    <% end %>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <head>
  <%= stylesheet_link_tag "application", 'https://fonts.googleapis.com/css?family=Ovo', :media => "all" %>
   <%= stylesheet_link_tag "application", 'https://fonts.googleapis.com/css?family=Muli', :media => "all" %>

    <title>Endorse Me</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
</head>

  <div class="wrapper">
    <body>
      <header>
       <h1> endorse.me</h1>
        <% if current_user %>
          <%= render 'pages/logedin' %>
        <% else %>
          <%= render 'pages/logedout' %>
        <% end %>
      </header>
      <%= yield %>
    </body>
  </div>
</html>

app/views/pages/_logedin.html.erb
<div class='userInfoCont'>
  <h4 id='userMsg'>Welcome, <%= current_user.first_name %>!</h4><br>
  <div class='homenav'>
    <%= button_to "Home",  root_path, method: :get, class: 'navbutton' %> <%= button_to "Log Out",  logout_path, method: :get, class: 'navbutton' %>
  </div>
</div>

app/views/pages/_logedout.html.erb
<div class='userInfoCont'>

  <h4 id='userMsg'>Login</h4><br>
   <%= form_for :user, url: '/login', method: :post do |f| %>
     <%= f.text_field :email, placeholder: 'email' %><br><br>
     <%= f.text_field :password, placeholder: 'password', type: 'password' %><br><br>
     <%= button_tag "Register",  action: '/register', method: :get, id: 'registerNow', class: 'navbutton' %>
     <%= f.submit 'Login', class: 'navbutton' %>
   <% end %>

</div>

app/views/pages/_register.html.erb
<div class='userInfoCont'>
  <h4 id='userMsg'>Sign up here:</h4><br>
  <%= form_for :user, url: '/register', method: :post, id: 'registerBox' do |f| %>
    <span id='signupform'> <%= f.text_field :first_name, placeholder: 'first name' %> <%= f.text_field :last_name, placeholder: 'last name' %></span>

    <%= f.text_field :email, placeholder: 'email' %>
    <%= f.text_field :password, placeholder: 'password', type: 'password' %><br><br>
    <%= f.submit 'Register', class: 'navbutton' %>
    <%= button_tag "Login",  action: '/login', method: :get, id: 'loginNow', class: 'navbutton'%>
  <% end %>


</div>

app/views/pages/show.html.erb
<div class='container'>
  <% if current_user %>
    <div id='profile'>
      <div id='bio'>
        <h2>About me:</h2>
        <p contentEditable=true> <%= current_user.bio %> </p>
        <%= button_tag 'Save Changes', method: :put, action: '/profile', id: 'bioEdit' %>
      </div>
      <div id='values'>
        <h2>Endorsements:</h2>
        <p><%= your_values.map {|v|v.word}.join(', ') %></p>
      </div>
    </div>
    <div id='friends'>
      <h2>Friends</h2>

      <%= button_tag 'My Friends',  method: :get, action: '/truefriends', id: 'friendslistButton' %>   <%= button_tag 'Friend Requests',  method: :get, action: '/requests', id: 'friendrequestButton' %>

      <%= form_tag('/search', method: :get, id: 'search') do %>
        <%= text_field_tag :email, nil, placeholder: 'search by email', class: 'searchBox' %>
        <%= submit_tag 'Search', class: 'searchButton' %>
      <% end -%>

      <ul id='friendlist'><ul>
    </div>

</div>
  <% else %>
  <div class="main">
    <p id="introq">Where do you excel?
    </p>
    <div class="super-wrapper">
      <div class="charfil">1. Connect with people who know you best.<br><Br>2. They endorse your people and programming skills. <br><br>3. Let the world know your strengths!
      </div>
      <div class="char1"><br><br><br>
        STRONG!<br><br><br><br><br><br><br><br>FASHIONABLE!<br><br><br><br><br><br><br>MAN OF HIS WORD!
      </div>
      <div class="superman">
      </div>
      <div class="char2"><br><br><br>
        INTELLECTUAL!<br><br><br><br><br><br><br><br>PERSISTENT!<br><br><br><br><br><br><br>JAVASCRIPT NINJA!
      </div><br>
    </div><br>
    <p class="intro">
    </p>
  </div>
  <% end %>
</div>

app/views/values/_addedvalues.html.erb
<p id="value_words">
  <% values.each do |value| %>
  <%= value.word %>,
  <% end %>

</p>

app/views/values/_iffriend.html.erb
<div id='addedvalues'>
  <h3> <%= friend.first_name %>'s endorsements:</h3>
  <%= render partial: 'values/addedvalues', locals: {values: values} %>
</div>

<div id='possiblevalues'>
  <h3>Endorse <%= friend.first_name %>:</h3>
  <%= form_tag(("/friends/#{friend.id}/addvalue"), method: :post, id: 'addvalue_form') do %>
    <%= text_field_tag :word, nil, placeholder: 'value' %>
    <%= submit_tag 'add' %>
  <% end %>

</div>

<div id='trendingvalues'>
  <br>
  <h3>click on possible skills to endorse:</h3>
  <%= render partial: 'values/possiblevalues', locals: {moreValues: moreValues, friend: friend} %>

  <%= button_tag 'see more',  method: :get, action: "/friend/#{friend.id}/values", id: 'morevalue_button' %>
</div>

app/views/values/_ifnotfriend.html.erb
<div id='friend_page_add'>

  <% if request_received %>
    <h3><%= friend.first_name %> added you.</h3>
    <h3>Add back to give values.</h3><br>

    <%= button_tag "add", action: "/friends/#{friend.id}/add_back", method: :patch, id: 'add_back_button' %>
  <% elsif request_sent %>
    <p id='request_sent_p'>Request already sent.</p>

  <% else %>
    <%= button_to "add #{friend.first_name} to give values", friend_path(friend),  method: :patch, id: 'send_request_button' %>

  <% end %>

</div>

app/views/values/_possiblevalues.html.erb
<p id="more_value_words">
  <% moreValues.map do |v| %>
    <a href="/friends/<%= friend.id %>/addvalue" value=<%= v.id %> class='value_a'><%= v.word %>, </a>
  <% end %>

</p>

app/views/values/friendvalues.html.erb
<div class="container">
    <h2> [ <%= friend.first_name %> <%= friend.last_name%> ]</h2>
  <div class="friendpage">

    <h2>About <%= friend.first_name %>: </h2><br><%= friend.bio %></br>

    <div id='addedvalues'>
  <h2> <%= friend.first_name %>'s best endorsements</h2>
  <% values[0..3].each do |value| %>
    <h3><%= value.word %></h3>
  <% end %>
</div>

  </div>

  <div id='friend_wrapper'>
    <% if values.length > 0 %>
      <%= render partial: 'values/iffriend', locals: {moreValues: moreValues, friend: friend, values: values, request_sent: request_sent}%>
    <% else %>
      <%= render partial: 'values/ifnotfriend', locals: {friend: friend, values: values, request_received: true, request_sent: request_sent}%>
    <% end %>
  </div>

</div>